name: "deploy workflow"

on:
  push:
    branches:
      - main

jobs:
  # build, test, deploy
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:    
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: model
          file: model/dockerfile
          push: true
          tags: temmie01/image-classifier:latest
      

        
      
