name: "deploy workflow"

on:
  push:
    branches:
      - main

jobs:
  # build, test, deploy
  build-and-push-image:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: model/
          file: model/dockerfile
          push: true
          tags: temmie01/image-classifier:latest

      - name: Deploy container
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker kill $(docker ps -q) && docker build -t temmie01/image-classifier:latest . && docker run -p 8080:8080  temmie01/image-classifier:latest
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_PK }}
      

        
      
